# Config file for RedstoneMobSpawner
Config:
  use_permissions: false
  use_tags: true
  redstoneblockcost: 10
  redstoneblockrefund: 5
RedstoneFaces: -NORTH -SOUTH -EAST -WEST
Mobs:
  CHICKEN: true
  CREEPER: true
  SKELETON: true
  SPIDER: true
  ZOMBIE: true
  SLIME: true
  GHAST: false
  PIG_ZOMBIE: false
  ENDERMAN: false
  CAVE_SPIDER: true
  SILVERFISH: false
  BLAZE: false
  MAGMA_CUBE: false
  ENDER_DRAGON: false
  WITHER: false
  BAT: true
  WITCH: false
  ENDERMITE: false
  GUARDIAN: false
  SHULKER: false
  SHEEP: true
  SQUID: true
  WOLF: true
  MUSHROOM_COW: true
  SNOWMAN: true
  OCELOT: true
  IRON_GOLEM: false
  HORSE: true
  RABBIT: true
  POLAR_BEAR: true
  LLAMA: true
  PARROT: true
  VILLAGER: false
  PIG: true
  COW: true
  STRAY: true
  HUSK: true
  ZOMBIE_VILLAGER: true
  SKELETON_HORSE: true
  ZOMBIE_HORSE: true
  DONKEY: true
  MULE: true
  EVOKER: true
  VEX: true
  VINDICATOR: true
  ILLUSIONER: true
  GIANT: true
  ZOMBIFIED_PIGLIN: true
  TURTLE: true
  PHANTOM: true
  DROWNED: true
  DOLPHIN: true
  CAT: true
  PANDA: true
  PILLAGER: true
  RAVAGER: true
  TRADER_LLAMA: true
  WANDERING_TRADER: true
  FOX: true
  BEE: true
  HOGLIN: true
  PIGLIN: true
  STRIDER: true
  ZOGLIN: true
RedstoneMobSpawners:
